/*******************************************************************************
 * Copyright © 2026 mousecray
 * Licensed under the GNU Lesser General Public License, Version 3.0
 ******************************************************************************/

package ru.mousecray.mouseproject.api.config;

import javax.annotation.Nonnull;

public enum ConfigLang {
    EN_US("English"), RU_RU("Русский"), UK_UA("Українська"),

    SQ_AL("Shqiptare"),
    AR_DZ("العربية"),
    AR_BH("العربية"),
    AR_EG("العربية"),
    AR_IQ("العربية"),
    AR_JO("العربية"),
    AR_KW("العربية"),
    AR_LB("العربية"),
    AR_LY("العربية"),
    AR_MA("العربية"),
    AR_OM("العربية"),
    AR_QA("العربية"),
    AR_SA("العربية"),
    AR_SD("العربية"),
    AR_SY("العربية"),
    AR_TN("العربية"),
    AR_AE("العربية"),
    AR_YE("العربية"),
    BE_BY("Беларускі"),
    BG_BG("Български"),
    CA_ES("Català"),
    ZH_CN("中文"),
    ZH_SG("中文"),
    ZH_HK("中文"),
    ZH_TW("中文"),
    HR_HR("Hrvatski"),
    CS_CZ("Čeština"),
    DA_DK("Dansk"),
    NL_BE("Nederlands"),
    NL_NL("Nederlands"),
    EN_AU("English"),
    EN_CA("English"),
    EN_IN("English"),
    EN_IE("English"),
    EN_MT("English"),
    EN_NZ("English"),
    EN_PH("English"),
    EN_SG("English"),
    EN_ZA("English"),
    EN_GB("English"),
    ET_EE("eesti keel"),
    FI_FI("suomalainen"),
    FR_BE("Français"),
    FR_CA("Français"),
    FR_FR("Français"),
    FR_LU("Français"),
    FR_CH("Français"),
    DE_AT("Deutsch"),
    DE_DE("Deutsch"),
    DE_LU("Deutsch"),
    DE_CH("Deutsch"),
    EL_CY("ελληνικά"),
    EL_GR("ελληνικά"),
    IW_IL("עִברִית"),
    HI_IN("हिन्दी"),
    HU_HU("magyar"),
    IS_IS("íslenskur"),
    IN_ID("Bahasa Indonesia"),
    GA_IE("Gaeilge"),
    IT_IT("Italiano"),
    IT_CH("Italiano"),
    JA_JP("日本語"),
    JA_JP_U_CA_JAPANESE("日本語"),
    JA_JP_X_LVARIANT_JP("日本語"),
    KO_KR("한국어"),
    LV_LV("latviski"),
    LT_LT("lietuvių"),
    MK_MK("македонски"),
    MS_MY("Melayu"),
    MT_MT("Malti"),
    NO_NO("norsk"),
    NB_NO("norsk bokmål"),
    NN_NO("norsk nynorsk"),
    NO_NO_X_LVARIANT_NY("norsk"),
    PL_PL("Polski"),
    PT_BR("Português"),
    PT_PT("Português"),
    RO_RO("română"),
    SR_BA("српски"),
    SR_ME("српски"),
    SR_RS("српски"),
    SR_LATN_BA("српски"),
    SR_LATN_ME("српски"),
    SR_LATN_RS("српски"),
    SK_SK("slovenský"),
    SL_SI("slovenski"),
    ES_AR("Español"),
    ES_BO("Español"),
    ES_CL("Español"),
    ES_CO("Español"),
    ES_CR("Español"),
    ES_DO("Español"),
    ES_EC("Español"),
    ES_SV("Español"),
    ES_GT("Español"),
    ES_HN("Español"),
    ES_MX("Español"),
    ES_NI("Español"),
    ES_PA("Español"),
    ES_PY("Español"),
    ES_PE("Español"),
    ES_PR("Español"),
    ES_ES("Español"),
    ES_US("Español"),
    ES_UY("Español"),
    ES_VE("Español"),
    SV_SE("svenska"),
    TH_TH("ไทย"),
    TH_TH_U_CA_BUDDHIST("ไทย"),
    TH_TH_U_CA_BUDDHIST_NU_THAI("ไทย"),
    TH_TH_X_LVARIANT_TH("ไทย"),
    TR_TR("Türkçe"),
    VI_VN("Tiếng Việt"),
    ;

    private final String displayName;
    ConfigLang(String displayName)          { this.displayName = displayName; }
    @Nonnull public String getDisplayName() { return displayName; }
}
